// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gamerpc/msg_kick.proto

package gamerpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NotifyKick struct {
	AccountId            int64    `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyKick) Reset()         { *m = NotifyKick{} }
func (m *NotifyKick) String() string { return proto.CompactTextString(m) }
func (*NotifyKick) ProtoMessage()    {}
func (*NotifyKick) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5a3030e7aa6ff05, []int{0}
}

func (m *NotifyKick) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyKick.Unmarshal(m, b)
}
func (m *NotifyKick) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyKick.Marshal(b, m, deterministic)
}
func (m *NotifyKick) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyKick.Merge(m, src)
}
func (m *NotifyKick) XXX_Size() int {
	return xxx_messageInfo_NotifyKick.Size(m)
}
func (m *NotifyKick) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyKick.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyKick proto.InternalMessageInfo

func (m *NotifyKick) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func init() {
	proto.RegisterType((*NotifyKick)(nil), "gamerpc.NotifyKick")
}

func init() {
	proto.RegisterFile("gamerpc/msg_kick.proto", fileDescriptor_e5a3030e7aa6ff05)
}

var fileDescriptor_e5a3030e7aa6ff05 = []byte{
	// 113 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4b, 0x4f, 0xcc, 0x4d,
	0x2d, 0x2a, 0x48, 0xd6, 0xcf, 0x2d, 0x4e, 0x8f, 0xcf, 0xce, 0x4c, 0xce, 0xd6, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x62, 0x87, 0x8a, 0x2b, 0x69, 0x73, 0x71, 0xf9, 0xe5, 0x97, 0x64, 0xa6, 0x55,
	0x7a, 0x67, 0x26, 0x67, 0x0b, 0xc9, 0x72, 0x71, 0x25, 0x26, 0x27, 0xe7, 0x97, 0xe6, 0x95, 0xc4,
	0x67, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x30, 0x07, 0x71, 0x42, 0x45, 0x3c, 0x53, 0x9c, 0xc4,
	0xa2, 0x44, 0xca, 0xd2, 0x0b, 0x8a, 0xf2, 0xb3, 0xf4, 0xc1, 0xa6, 0xe8, 0x43, 0x0d, 0x49, 0x62,
	0x03, 0x73, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x26, 0xdd, 0x98, 0x77, 0x6e, 0x00, 0x00,
	0x00,
}
