// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg/msg_settings.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type S2C_PlayerSettings struct {
	Lan                  int32    `protobuf:"varint,1,opt,name=lan,proto3" json:"lan,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2C_PlayerSettings) Reset()         { *m = S2C_PlayerSettings{} }
func (m *S2C_PlayerSettings) String() string { return proto.CompactTextString(m) }
func (*S2C_PlayerSettings) ProtoMessage()    {}
func (*S2C_PlayerSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fb461d976a24ce0, []int{0}
}

func (m *S2C_PlayerSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C_PlayerSettings.Unmarshal(m, b)
}
func (m *S2C_PlayerSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C_PlayerSettings.Marshal(b, m, deterministic)
}
func (m *S2C_PlayerSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C_PlayerSettings.Merge(m, src)
}
func (m *S2C_PlayerSettings) XXX_Size() int {
	return xxx_messageInfo_S2C_PlayerSettings.Size(m)
}
func (m *S2C_PlayerSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C_PlayerSettings.DiscardUnknown(m)
}

var xxx_messageInfo_S2C_PlayerSettings proto.InternalMessageInfo

func (m *S2C_PlayerSettings) GetLan() int32 {
	if m != nil {
		return m.Lan
	}
	return 0
}

func init() {
	proto.RegisterType((*S2C_PlayerSettings)(nil), "msg.S2C_PlayerSettings")
}

func init() {
	proto.RegisterFile("msg/msg_settings.proto", fileDescriptor_4fb461d976a24ce0)
}

var fileDescriptor_4fb461d976a24ce0 = []byte{
	// 107 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcb, 0x2d, 0x4e, 0xd7,
	0xcf, 0x2d, 0x4e, 0x8f, 0x2f, 0x4e, 0x2d, 0x29, 0xc9, 0xcc, 0x4b, 0x2f, 0xd6, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x62, 0xce, 0x2d, 0x4e, 0x57, 0x52, 0xe3, 0x12, 0x0a, 0x36, 0x72, 0x8e, 0x0f,
	0xc8, 0x49, 0xac, 0x4c, 0x2d, 0x0a, 0x86, 0x2a, 0x10, 0x12, 0xe0, 0x62, 0xce, 0x49, 0xcc, 0x93,
	0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x02, 0x31, 0x9d, 0x84, 0xa3, 0x04, 0xcb, 0xd2, 0xe3, 0x0b,
	0x8a, 0xf2, 0xb3, 0xf4, 0xc1, 0xba, 0x41, 0x06, 0x26, 0xb1, 0x81, 0x99, 0xc6, 0x80, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x03, 0x91, 0x74, 0xe0, 0x62, 0x00, 0x00, 0x00,
}
