// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg/msg_hero.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Hero struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Star                 int32    `protobuf:"varint,2,opt,name=star,proto3" json:"star,omitempty"`
	Lev                  int64    `protobuf:"varint,3,opt,name=lev,proto3" json:"lev,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hero) Reset()         { *m = Hero{} }
func (m *Hero) String() string { return proto.CompactTextString(m) }
func (*Hero) ProtoMessage()    {}
func (*Hero) Descriptor() ([]byte, []int) {
	return fileDescriptor_649ab708a3df73e3, []int{0}
}

func (m *Hero) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hero.Unmarshal(m, b)
}
func (m *Hero) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hero.Marshal(b, m, deterministic)
}
func (m *Hero) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hero.Merge(m, src)
}
func (m *Hero) XXX_Size() int {
	return xxx_messageInfo_Hero.Size(m)
}
func (m *Hero) XXX_DiscardUnknown() {
	xxx_messageInfo_Hero.DiscardUnknown(m)
}

var xxx_messageInfo_Hero proto.InternalMessageInfo

func (m *Hero) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Hero) GetStar() int32 {
	if m != nil {
		return m.Star
	}
	return 0
}

func (m *Hero) GetLev() int64 {
	if m != nil {
		return m.Lev
	}
	return 0
}

type S2C_HeroList struct {
	Heroes               []*Hero  `protobuf:"bytes,1,rep,name=heroes,proto3" json:"heroes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2C_HeroList) Reset()         { *m = S2C_HeroList{} }
func (m *S2C_HeroList) String() string { return proto.CompactTextString(m) }
func (*S2C_HeroList) ProtoMessage()    {}
func (*S2C_HeroList) Descriptor() ([]byte, []int) {
	return fileDescriptor_649ab708a3df73e3, []int{1}
}

func (m *S2C_HeroList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C_HeroList.Unmarshal(m, b)
}
func (m *S2C_HeroList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C_HeroList.Marshal(b, m, deterministic)
}
func (m *S2C_HeroList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C_HeroList.Merge(m, src)
}
func (m *S2C_HeroList) XXX_Size() int {
	return xxx_messageInfo_S2C_HeroList.Size(m)
}
func (m *S2C_HeroList) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C_HeroList.DiscardUnknown(m)
}

var xxx_messageInfo_S2C_HeroList proto.InternalMessageInfo

func (m *S2C_HeroList) GetHeroes() []*Hero {
	if m != nil {
		return m.Heroes
	}
	return nil
}

type C2S_UpgradeHeroLevReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UpLev                int64    `protobuf:"varint,2,opt,name=up_lev,json=upLev,proto3" json:"up_lev,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2S_UpgradeHeroLevReq) Reset()         { *m = C2S_UpgradeHeroLevReq{} }
func (m *C2S_UpgradeHeroLevReq) String() string { return proto.CompactTextString(m) }
func (*C2S_UpgradeHeroLevReq) ProtoMessage()    {}
func (*C2S_UpgradeHeroLevReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_649ab708a3df73e3, []int{2}
}

func (m *C2S_UpgradeHeroLevReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2S_UpgradeHeroLevReq.Unmarshal(m, b)
}
func (m *C2S_UpgradeHeroLevReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2S_UpgradeHeroLevReq.Marshal(b, m, deterministic)
}
func (m *C2S_UpgradeHeroLevReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2S_UpgradeHeroLevReq.Merge(m, src)
}
func (m *C2S_UpgradeHeroLevReq) XXX_Size() int {
	return xxx_messageInfo_C2S_UpgradeHeroLevReq.Size(m)
}
func (m *C2S_UpgradeHeroLevReq) XXX_DiscardUnknown() {
	xxx_messageInfo_C2S_UpgradeHeroLevReq.DiscardUnknown(m)
}

var xxx_messageInfo_C2S_UpgradeHeroLevReq proto.InternalMessageInfo

func (m *C2S_UpgradeHeroLevReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *C2S_UpgradeHeroLevReq) GetUpLev() int64 {
	if m != nil {
		return m.UpLev
	}
	return 0
}

type S2C_UpgradeHeroLevRsp struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	UpLev                int64    `protobuf:"varint,3,opt,name=up_lev,json=upLev,proto3" json:"up_lev,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2C_UpgradeHeroLevRsp) Reset()         { *m = S2C_UpgradeHeroLevRsp{} }
func (m *S2C_UpgradeHeroLevRsp) String() string { return proto.CompactTextString(m) }
func (*S2C_UpgradeHeroLevRsp) ProtoMessage()    {}
func (*S2C_UpgradeHeroLevRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_649ab708a3df73e3, []int{3}
}

func (m *S2C_UpgradeHeroLevRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C_UpgradeHeroLevRsp.Unmarshal(m, b)
}
func (m *S2C_UpgradeHeroLevRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C_UpgradeHeroLevRsp.Marshal(b, m, deterministic)
}
func (m *S2C_UpgradeHeroLevRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C_UpgradeHeroLevRsp.Merge(m, src)
}
func (m *S2C_UpgradeHeroLevRsp) XXX_Size() int {
	return xxx_messageInfo_S2C_UpgradeHeroLevRsp.Size(m)
}
func (m *S2C_UpgradeHeroLevRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C_UpgradeHeroLevRsp.DiscardUnknown(m)
}

var xxx_messageInfo_S2C_UpgradeHeroLevRsp proto.InternalMessageInfo

func (m *S2C_UpgradeHeroLevRsp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *S2C_UpgradeHeroLevRsp) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *S2C_UpgradeHeroLevRsp) GetUpLev() int64 {
	if m != nil {
		return m.UpLev
	}
	return 0
}

type C2S_UpgradeHeroStarReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UpStar               int32    `protobuf:"varint,2,opt,name=up_star,json=upStar,proto3" json:"up_star,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2S_UpgradeHeroStarReq) Reset()         { *m = C2S_UpgradeHeroStarReq{} }
func (m *C2S_UpgradeHeroStarReq) String() string { return proto.CompactTextString(m) }
func (*C2S_UpgradeHeroStarReq) ProtoMessage()    {}
func (*C2S_UpgradeHeroStarReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_649ab708a3df73e3, []int{4}
}

func (m *C2S_UpgradeHeroStarReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2S_UpgradeHeroStarReq.Unmarshal(m, b)
}
func (m *C2S_UpgradeHeroStarReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2S_UpgradeHeroStarReq.Marshal(b, m, deterministic)
}
func (m *C2S_UpgradeHeroStarReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2S_UpgradeHeroStarReq.Merge(m, src)
}
func (m *C2S_UpgradeHeroStarReq) XXX_Size() int {
	return xxx_messageInfo_C2S_UpgradeHeroStarReq.Size(m)
}
func (m *C2S_UpgradeHeroStarReq) XXX_DiscardUnknown() {
	xxx_messageInfo_C2S_UpgradeHeroStarReq.DiscardUnknown(m)
}

var xxx_messageInfo_C2S_UpgradeHeroStarReq proto.InternalMessageInfo

func (m *C2S_UpgradeHeroStarReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *C2S_UpgradeHeroStarReq) GetUpStar() int32 {
	if m != nil {
		return m.UpStar
	}
	return 0
}

type S2C_UpgradeHeroStarRsp struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	UpStar               int32    `protobuf:"varint,3,opt,name=up_star,json=upStar,proto3" json:"up_star,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2C_UpgradeHeroStarRsp) Reset()         { *m = S2C_UpgradeHeroStarRsp{} }
func (m *S2C_UpgradeHeroStarRsp) String() string { return proto.CompactTextString(m) }
func (*S2C_UpgradeHeroStarRsp) ProtoMessage()    {}
func (*S2C_UpgradeHeroStarRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_649ab708a3df73e3, []int{5}
}

func (m *S2C_UpgradeHeroStarRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C_UpgradeHeroStarRsp.Unmarshal(m, b)
}
func (m *S2C_UpgradeHeroStarRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C_UpgradeHeroStarRsp.Marshal(b, m, deterministic)
}
func (m *S2C_UpgradeHeroStarRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C_UpgradeHeroStarRsp.Merge(m, src)
}
func (m *S2C_UpgradeHeroStarRsp) XXX_Size() int {
	return xxx_messageInfo_S2C_UpgradeHeroStarRsp.Size(m)
}
func (m *S2C_UpgradeHeroStarRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C_UpgradeHeroStarRsp.DiscardUnknown(m)
}

var xxx_messageInfo_S2C_UpgradeHeroStarRsp proto.InternalMessageInfo

func (m *S2C_UpgradeHeroStarRsp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *S2C_UpgradeHeroStarRsp) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *S2C_UpgradeHeroStarRsp) GetUpStar() int32 {
	if m != nil {
		return m.UpStar
	}
	return 0
}

func init() {
	proto.RegisterType((*Hero)(nil), "msg.Hero")
	proto.RegisterType((*S2C_HeroList)(nil), "msg.S2C_HeroList")
	proto.RegisterType((*C2S_UpgradeHeroLevReq)(nil), "msg.C2S_UpgradeHeroLevReq")
	proto.RegisterType((*S2C_UpgradeHeroLevRsp)(nil), "msg.S2C_UpgradeHeroLevRsp")
	proto.RegisterType((*C2S_UpgradeHeroStarReq)(nil), "msg.C2S_UpgradeHeroStarReq")
	proto.RegisterType((*S2C_UpgradeHeroStarRsp)(nil), "msg.S2C_UpgradeHeroStarRsp")
}

func init() {
	proto.RegisterFile("msg/msg_hero.proto", fileDescriptor_649ab708a3df73e3)
}

var fileDescriptor_649ab708a3df73e3 = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xb1, 0x4f, 0x84, 0x30,
	0x14, 0xc6, 0x43, 0x7b, 0x87, 0xf1, 0x69, 0x8c, 0xd6, 0x70, 0x32, 0x62, 0x27, 0x26, 0x2e, 0xe2,
	0x6a, 0x4c, 0xf4, 0x16, 0x87, 0x9b, 0x4a, 0x6e, 0x71, 0x69, 0x50, 0x9a, 0x8a, 0x91, 0xb4, 0xb6,
	0xc0, 0xdf, 0x6f, 0x5e, 0xc3, 0x40, 0xf0, 0x86, 0xdb, 0xbe, 0xf0, 0x78, 0xbf, 0xef, 0x97, 0x3e,
	0x60, 0x9d, 0xd7, 0xdb, 0xce, 0x6b, 0xf9, 0xa5, 0x9c, 0x29, 0xac, 0x33, 0xbd, 0x61, 0xb4, 0xf3,
	0x9a, 0x3f, 0xc1, 0xea, 0x4d, 0x39, 0xc3, 0xae, 0x80, 0xb4, 0x4d, 0x1a, 0x65, 0x51, 0xbe, 0x16,
	0xa4, 0x6d, 0x18, 0x83, 0x95, 0xef, 0x6b, 0x97, 0x92, 0xf0, 0x25, 0x64, 0x76, 0x0d, 0xf4, 0x47,
	0x8d, 0x29, 0xcd, 0xa2, 0x9c, 0x0a, 0x8c, 0xfc, 0x01, 0x2e, 0xab, 0x72, 0x27, 0x91, 0xb0, 0x6f,
	0x7d, 0xcf, 0xee, 0x21, 0xc6, 0x02, 0xe5, 0xd3, 0x28, 0xa3, 0xf9, 0x45, 0x79, 0x5e, 0x74, 0x5e,
	0x17, 0x38, 0x16, 0xd3, 0x80, 0x3f, 0x43, 0xb2, 0x2b, 0x2b, 0x79, 0xb0, 0xda, 0xd5, 0x8d, 0x0a,
	0x9b, 0x6a, 0x14, 0xea, 0xf7, 0x9f, 0x41, 0x02, 0xf1, 0x60, 0x25, 0x16, 0x92, 0x50, 0xb8, 0x1e,
	0xec, 0x5e, 0x8d, 0x5c, 0x40, 0x82, 0x95, 0x8b, 0x7d, 0x6f, 0xd1, 0xf8, 0xd3, 0x34, 0x6a, 0x22,
	0x84, 0x3c, 0x31, 0xc9, 0x11, 0x26, 0x9d, 0x33, 0x5f, 0x60, 0xb3, 0x70, 0xaa, 0xfa, 0xda, 0x1d,
	0x93, 0xba, 0x83, 0xb3, 0xc1, 0xca, 0xd9, 0xcb, 0xc4, 0x83, 0xc5, 0x7f, 0xf9, 0x01, 0x36, 0x0b,
	0xad, 0x80, 0x38, 0xd1, 0x6b, 0x86, 0xa5, 0x73, 0xec, 0xeb, 0xed, 0xfb, 0xcd, 0xa8, 0xa5, 0x75,
	0xe6, 0x7b, 0x1b, 0x8e, 0x86, 0x37, 0xfc, 0x88, 0x43, 0x7c, 0xfc, 0x0b, 0x00, 0x00, 0xff, 0xff,
	0x09, 0x88, 0x5c, 0xa4, 0xd5, 0x01, 0x00, 0x00,
}
