// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg/msg_vip.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type S2C_VIP_NOTIFY struct {
	VipLev               int32    `protobuf:"varint,1,opt,name=vip_lev,json=vipLev,proto3" json:"vip_lev,omitempty"`
	VipExp               int32    `protobuf:"varint,2,opt,name=vip_exp,json=vipExp,proto3" json:"vip_exp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2C_VIP_NOTIFY) Reset()         { *m = S2C_VIP_NOTIFY{} }
func (m *S2C_VIP_NOTIFY) String() string { return proto.CompactTextString(m) }
func (*S2C_VIP_NOTIFY) ProtoMessage()    {}
func (*S2C_VIP_NOTIFY) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ef8f7cf2b4d535, []int{0}
}

func (m *S2C_VIP_NOTIFY) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C_VIP_NOTIFY.Unmarshal(m, b)
}
func (m *S2C_VIP_NOTIFY) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C_VIP_NOTIFY.Marshal(b, m, deterministic)
}
func (m *S2C_VIP_NOTIFY) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C_VIP_NOTIFY.Merge(m, src)
}
func (m *S2C_VIP_NOTIFY) XXX_Size() int {
	return xxx_messageInfo_S2C_VIP_NOTIFY.Size(m)
}
func (m *S2C_VIP_NOTIFY) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C_VIP_NOTIFY.DiscardUnknown(m)
}

var xxx_messageInfo_S2C_VIP_NOTIFY proto.InternalMessageInfo

func (m *S2C_VIP_NOTIFY) GetVipLev() int32 {
	if m != nil {
		return m.VipLev
	}
	return 0
}

func (m *S2C_VIP_NOTIFY) GetVipExp() int32 {
	if m != nil {
		return m.VipExp
	}
	return 0
}

type VIP_GIFT_STATUS struct {
	VipLev               int32    `protobuf:"varint,1,opt,name=vip_lev,json=vipLev,proto3" json:"vip_lev,omitempty"`
	GetReward            int32    `protobuf:"varint,2,opt,name=get_reward,json=getReward,proto3" json:"get_reward,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VIP_GIFT_STATUS) Reset()         { *m = VIP_GIFT_STATUS{} }
func (m *VIP_GIFT_STATUS) String() string { return proto.CompactTextString(m) }
func (*VIP_GIFT_STATUS) ProtoMessage()    {}
func (*VIP_GIFT_STATUS) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ef8f7cf2b4d535, []int{1}
}

func (m *VIP_GIFT_STATUS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VIP_GIFT_STATUS.Unmarshal(m, b)
}
func (m *VIP_GIFT_STATUS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VIP_GIFT_STATUS.Marshal(b, m, deterministic)
}
func (m *VIP_GIFT_STATUS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VIP_GIFT_STATUS.Merge(m, src)
}
func (m *VIP_GIFT_STATUS) XXX_Size() int {
	return xxx_messageInfo_VIP_GIFT_STATUS.Size(m)
}
func (m *VIP_GIFT_STATUS) XXX_DiscardUnknown() {
	xxx_messageInfo_VIP_GIFT_STATUS.DiscardUnknown(m)
}

var xxx_messageInfo_VIP_GIFT_STATUS proto.InternalMessageInfo

func (m *VIP_GIFT_STATUS) GetVipLev() int32 {
	if m != nil {
		return m.VipLev
	}
	return 0
}

func (m *VIP_GIFT_STATUS) GetGetReward() int32 {
	if m != nil {
		return m.GetReward
	}
	return 0
}

type C2S_VIP_GET_GIFT_STATUS struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2S_VIP_GET_GIFT_STATUS) Reset()         { *m = C2S_VIP_GET_GIFT_STATUS{} }
func (m *C2S_VIP_GET_GIFT_STATUS) String() string { return proto.CompactTextString(m) }
func (*C2S_VIP_GET_GIFT_STATUS) ProtoMessage()    {}
func (*C2S_VIP_GET_GIFT_STATUS) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ef8f7cf2b4d535, []int{2}
}

func (m *C2S_VIP_GET_GIFT_STATUS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2S_VIP_GET_GIFT_STATUS.Unmarshal(m, b)
}
func (m *C2S_VIP_GET_GIFT_STATUS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2S_VIP_GET_GIFT_STATUS.Marshal(b, m, deterministic)
}
func (m *C2S_VIP_GET_GIFT_STATUS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2S_VIP_GET_GIFT_STATUS.Merge(m, src)
}
func (m *C2S_VIP_GET_GIFT_STATUS) XXX_Size() int {
	return xxx_messageInfo_C2S_VIP_GET_GIFT_STATUS.Size(m)
}
func (m *C2S_VIP_GET_GIFT_STATUS) XXX_DiscardUnknown() {
	xxx_messageInfo_C2S_VIP_GET_GIFT_STATUS.DiscardUnknown(m)
}

var xxx_messageInfo_C2S_VIP_GET_GIFT_STATUS proto.InternalMessageInfo

type S2C_VIP_GET_GIFT_STATUS struct {
	Code                 int32              `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Status               []*VIP_GIFT_STATUS `protobuf:"bytes,2,rep,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *S2C_VIP_GET_GIFT_STATUS) Reset()         { *m = S2C_VIP_GET_GIFT_STATUS{} }
func (m *S2C_VIP_GET_GIFT_STATUS) String() string { return proto.CompactTextString(m) }
func (*S2C_VIP_GET_GIFT_STATUS) ProtoMessage()    {}
func (*S2C_VIP_GET_GIFT_STATUS) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ef8f7cf2b4d535, []int{3}
}

func (m *S2C_VIP_GET_GIFT_STATUS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C_VIP_GET_GIFT_STATUS.Unmarshal(m, b)
}
func (m *S2C_VIP_GET_GIFT_STATUS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C_VIP_GET_GIFT_STATUS.Marshal(b, m, deterministic)
}
func (m *S2C_VIP_GET_GIFT_STATUS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C_VIP_GET_GIFT_STATUS.Merge(m, src)
}
func (m *S2C_VIP_GET_GIFT_STATUS) XXX_Size() int {
	return xxx_messageInfo_S2C_VIP_GET_GIFT_STATUS.Size(m)
}
func (m *S2C_VIP_GET_GIFT_STATUS) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C_VIP_GET_GIFT_STATUS.DiscardUnknown(m)
}

var xxx_messageInfo_S2C_VIP_GET_GIFT_STATUS proto.InternalMessageInfo

func (m *S2C_VIP_GET_GIFT_STATUS) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *S2C_VIP_GET_GIFT_STATUS) GetStatus() []*VIP_GIFT_STATUS {
	if m != nil {
		return m.Status
	}
	return nil
}

type C2S_VIP_COLLECT_GIFT struct {
	GiftLev              int32    `protobuf:"varint,1,opt,name=gift_lev,json=giftLev,proto3" json:"gift_lev,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2S_VIP_COLLECT_GIFT) Reset()         { *m = C2S_VIP_COLLECT_GIFT{} }
func (m *C2S_VIP_COLLECT_GIFT) String() string { return proto.CompactTextString(m) }
func (*C2S_VIP_COLLECT_GIFT) ProtoMessage()    {}
func (*C2S_VIP_COLLECT_GIFT) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ef8f7cf2b4d535, []int{4}
}

func (m *C2S_VIP_COLLECT_GIFT) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2S_VIP_COLLECT_GIFT.Unmarshal(m, b)
}
func (m *C2S_VIP_COLLECT_GIFT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2S_VIP_COLLECT_GIFT.Marshal(b, m, deterministic)
}
func (m *C2S_VIP_COLLECT_GIFT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2S_VIP_COLLECT_GIFT.Merge(m, src)
}
func (m *C2S_VIP_COLLECT_GIFT) XXX_Size() int {
	return xxx_messageInfo_C2S_VIP_COLLECT_GIFT.Size(m)
}
func (m *C2S_VIP_COLLECT_GIFT) XXX_DiscardUnknown() {
	xxx_messageInfo_C2S_VIP_COLLECT_GIFT.DiscardUnknown(m)
}

var xxx_messageInfo_C2S_VIP_COLLECT_GIFT proto.InternalMessageInfo

func (m *C2S_VIP_COLLECT_GIFT) GetGiftLev() int32 {
	if m != nil {
		return m.GiftLev
	}
	return 0
}

type S2C_VIP_COLLECT_GIFT struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	GiftLev              int32    `protobuf:"varint,2,opt,name=gift_lev,json=giftLev,proto3" json:"gift_lev,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2C_VIP_COLLECT_GIFT) Reset()         { *m = S2C_VIP_COLLECT_GIFT{} }
func (m *S2C_VIP_COLLECT_GIFT) String() string { return proto.CompactTextString(m) }
func (*S2C_VIP_COLLECT_GIFT) ProtoMessage()    {}
func (*S2C_VIP_COLLECT_GIFT) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ef8f7cf2b4d535, []int{5}
}

func (m *S2C_VIP_COLLECT_GIFT) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C_VIP_COLLECT_GIFT.Unmarshal(m, b)
}
func (m *S2C_VIP_COLLECT_GIFT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C_VIP_COLLECT_GIFT.Marshal(b, m, deterministic)
}
func (m *S2C_VIP_COLLECT_GIFT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C_VIP_COLLECT_GIFT.Merge(m, src)
}
func (m *S2C_VIP_COLLECT_GIFT) XXX_Size() int {
	return xxx_messageInfo_S2C_VIP_COLLECT_GIFT.Size(m)
}
func (m *S2C_VIP_COLLECT_GIFT) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C_VIP_COLLECT_GIFT.DiscardUnknown(m)
}

var xxx_messageInfo_S2C_VIP_COLLECT_GIFT proto.InternalMessageInfo

func (m *S2C_VIP_COLLECT_GIFT) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *S2C_VIP_COLLECT_GIFT) GetGiftLev() int32 {
	if m != nil {
		return m.GiftLev
	}
	return 0
}

func init() {
	proto.RegisterType((*S2C_VIP_NOTIFY)(nil), "msg.S2C_VIP_NOTIFY")
	proto.RegisterType((*VIP_GIFT_STATUS)(nil), "msg.VIP_GIFT_STATUS")
	proto.RegisterType((*C2S_VIP_GET_GIFT_STATUS)(nil), "msg.C2S_VIP_GET_GIFT_STATUS")
	proto.RegisterType((*S2C_VIP_GET_GIFT_STATUS)(nil), "msg.S2C_VIP_GET_GIFT_STATUS")
	proto.RegisterType((*C2S_VIP_COLLECT_GIFT)(nil), "msg.C2S_VIP_COLLECT_GIFT")
	proto.RegisterType((*S2C_VIP_COLLECT_GIFT)(nil), "msg.S2C_VIP_COLLECT_GIFT")
}

func init() {
	proto.RegisterFile("msg/msg_vip.proto", fileDescriptor_d6ef8f7cf2b4d535)
}

var fileDescriptor_d6ef8f7cf2b4d535 = []byte{
	// 273 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x59, 0xa7, 0x9d, 0x3e, 0x41, 0x59, 0x2c, 0xb4, 0x3b, 0x08, 0x23, 0xa7, 0x1d, 0xa4,
	0xc3, 0xfa, 0x09, 0x5c, 0xe9, 0x46, 0xa1, 0x38, 0x69, 0xa3, 0xa0, 0x1e, 0xc2, 0x74, 0x31, 0x54,
	0x2c, 0x0d, 0x4d, 0x8c, 0xfb, 0xf8, 0xd2, 0xd8, 0x4a, 0x57, 0xf4, 0xf6, 0x92, 0x97, 0xf7, 0xfb,
	0xff, 0xc2, 0x83, 0x71, 0x21, 0xf9, 0xbc, 0x90, 0x9c, 0xea, 0x5c, 0xf8, 0xa2, 0x2a, 0x55, 0x89,
	0x86, 0x85, 0xe4, 0x78, 0x01, 0xa7, 0x59, 0x10, 0xd2, 0x87, 0xf8, 0x8e, 0xde, 0xae, 0x49, 0xbc,
	0x7c, 0x44, 0x2e, 0x8c, 0x74, 0x2e, 0xe8, 0x07, 0xd3, 0xde, 0x60, 0x3a, 0x98, 0x1d, 0xa6, 0xb6,
	0xce, 0x45, 0xc2, 0x74, 0xdb, 0x60, 0x3b, 0xe1, 0x59, 0xbf, 0x8d, 0x68, 0x27, 0x70, 0x0c, 0x67,
	0xf5, 0xfc, 0x2a, 0x5e, 0x12, 0x9a, 0x91, 0x1b, 0x72, 0x9f, 0xfd, 0x0f, 0xb9, 0x00, 0xe0, 0x4c,
	0xd1, 0x8a, 0x7d, 0x6d, 0xaa, 0x6d, 0xc3, 0x39, 0xe6, 0x4c, 0xa5, 0xe6, 0x02, 0x4f, 0xc0, 0x0d,
	0x83, 0xcc, 0xe8, 0xac, 0x22, 0xd2, 0x45, 0xe2, 0x67, 0x70, 0x5b, 0xd3, 0x5e, 0x0b, 0x21, 0x38,
	0x78, 0x2d, 0xb7, 0xac, 0x89, 0x32, 0x35, 0xba, 0x04, 0x5b, 0xaa, 0x8d, 0xfa, 0x94, 0x9e, 0x35,
	0x1d, 0xce, 0x4e, 0x02, 0xc7, 0x2f, 0x24, 0xf7, 0x7b, 0x9e, 0x69, 0xf3, 0x06, 0x5f, 0x81, 0xd3,
	0xe6, 0x86, 0xeb, 0x24, 0x89, 0xc2, 0x9f, 0x00, 0x34, 0x81, 0x23, 0x9e, 0xbf, 0xa9, 0xce, 0x47,
	0x46, 0xf5, 0x39, 0x61, 0x1a, 0x47, 0xe0, 0xb4, 0x3e, 0x7b, 0x23, 0x7f, 0xc9, 0x74, 0x31, 0xd6,
	0x1e, 0x66, 0x71, 0xfe, 0x34, 0xd6, 0x9c, 0x8a, 0xaa, 0x7c, 0x9f, 0x9b, 0xb5, 0xd4, 0x4b, 0x7a,
	0xb1, 0x4d, 0x79, 0xfd, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xdf, 0x14, 0xd4, 0x51, 0xb6, 0x01, 0x00,
	0x00,
}
