// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg/msg_login.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type C2S_Login struct {
	AccountId            int64    `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	ServerId             int32    `protobuf:"varint,3,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2S_Login) Reset()         { *m = C2S_Login{} }
func (m *C2S_Login) String() string { return proto.CompactTextString(m) }
func (*C2S_Login) ProtoMessage()    {}
func (*C2S_Login) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8ef43988e3693e5, []int{0}
}

func (m *C2S_Login) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2S_Login.Unmarshal(m, b)
}
func (m *C2S_Login) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2S_Login.Marshal(b, m, deterministic)
}
func (m *C2S_Login) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2S_Login.Merge(m, src)
}
func (m *C2S_Login) XXX_Size() int {
	return xxx_messageInfo_C2S_Login.Size(m)
}
func (m *C2S_Login) XXX_DiscardUnknown() {
	xxx_messageInfo_C2S_Login.DiscardUnknown(m)
}

var xxx_messageInfo_C2S_Login proto.InternalMessageInfo

func (m *C2S_Login) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *C2S_Login) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *C2S_Login) GetServerId() int32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

type S2C_Login struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	PlayerId             int64    `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	ServerTime           int64    `protobuf:"varint,3,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	Offset               int32    `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	OpenServerTime       int64    `protobuf:"varint,5,opt,name=open_server_time,json=openServerTime,proto3" json:"open_server_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2C_Login) Reset()         { *m = S2C_Login{} }
func (m *S2C_Login) String() string { return proto.CompactTextString(m) }
func (*S2C_Login) ProtoMessage()    {}
func (*S2C_Login) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8ef43988e3693e5, []int{1}
}

func (m *S2C_Login) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C_Login.Unmarshal(m, b)
}
func (m *S2C_Login) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C_Login.Marshal(b, m, deterministic)
}
func (m *S2C_Login) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C_Login.Merge(m, src)
}
func (m *S2C_Login) XXX_Size() int {
	return xxx_messageInfo_S2C_Login.Size(m)
}
func (m *S2C_Login) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C_Login.DiscardUnknown(m)
}

var xxx_messageInfo_S2C_Login proto.InternalMessageInfo

func (m *S2C_Login) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *S2C_Login) GetPlayerId() int64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *S2C_Login) GetServerTime() int64 {
	if m != nil {
		return m.ServerTime
	}
	return 0
}

func (m *S2C_Login) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *S2C_Login) GetOpenServerTime() int64 {
	if m != nil {
		return m.OpenServerTime
	}
	return 0
}

type C2S_CreateCharacter struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Head                 int32    `protobuf:"varint,2,opt,name=head,proto3" json:"head,omitempty"`
	Sex                  int32    `protobuf:"varint,3,opt,name=sex,proto3" json:"sex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2S_CreateCharacter) Reset()         { *m = C2S_CreateCharacter{} }
func (m *C2S_CreateCharacter) String() string { return proto.CompactTextString(m) }
func (*C2S_CreateCharacter) ProtoMessage()    {}
func (*C2S_CreateCharacter) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8ef43988e3693e5, []int{2}
}

func (m *C2S_CreateCharacter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2S_CreateCharacter.Unmarshal(m, b)
}
func (m *C2S_CreateCharacter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2S_CreateCharacter.Marshal(b, m, deterministic)
}
func (m *C2S_CreateCharacter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2S_CreateCharacter.Merge(m, src)
}
func (m *C2S_CreateCharacter) XXX_Size() int {
	return xxx_messageInfo_C2S_CreateCharacter.Size(m)
}
func (m *C2S_CreateCharacter) XXX_DiscardUnknown() {
	xxx_messageInfo_C2S_CreateCharacter.DiscardUnknown(m)
}

var xxx_messageInfo_C2S_CreateCharacter proto.InternalMessageInfo

func (m *C2S_CreateCharacter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *C2S_CreateCharacter) GetHead() int32 {
	if m != nil {
		return m.Head
	}
	return 0
}

func (m *C2S_CreateCharacter) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

type S2C_CreateCharacter struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	PlayerId             int64    `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2C_CreateCharacter) Reset()         { *m = S2C_CreateCharacter{} }
func (m *S2C_CreateCharacter) String() string { return proto.CompactTextString(m) }
func (*S2C_CreateCharacter) ProtoMessage()    {}
func (*S2C_CreateCharacter) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8ef43988e3693e5, []int{3}
}

func (m *S2C_CreateCharacter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C_CreateCharacter.Unmarshal(m, b)
}
func (m *S2C_CreateCharacter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C_CreateCharacter.Marshal(b, m, deterministic)
}
func (m *S2C_CreateCharacter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C_CreateCharacter.Merge(m, src)
}
func (m *S2C_CreateCharacter) XXX_Size() int {
	return xxx_messageInfo_S2C_CreateCharacter.Size(m)
}
func (m *S2C_CreateCharacter) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C_CreateCharacter.DiscardUnknown(m)
}

var xxx_messageInfo_S2C_CreateCharacter proto.InternalMessageInfo

func (m *S2C_CreateCharacter) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *S2C_CreateCharacter) GetPlayerId() int64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

type S2C_Disconnect struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2C_Disconnect) Reset()         { *m = S2C_Disconnect{} }
func (m *S2C_Disconnect) String() string { return proto.CompactTextString(m) }
func (*S2C_Disconnect) ProtoMessage()    {}
func (*S2C_Disconnect) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8ef43988e3693e5, []int{4}
}

func (m *S2C_Disconnect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C_Disconnect.Unmarshal(m, b)
}
func (m *S2C_Disconnect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C_Disconnect.Marshal(b, m, deterministic)
}
func (m *S2C_Disconnect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C_Disconnect.Merge(m, src)
}
func (m *S2C_Disconnect) XXX_Size() int {
	return xxx_messageInfo_S2C_Disconnect.Size(m)
}
func (m *S2C_Disconnect) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C_Disconnect.DiscardUnknown(m)
}

var xxx_messageInfo_S2C_Disconnect proto.InternalMessageInfo

func (m *S2C_Disconnect) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type S2C_LoginFinish struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2C_LoginFinish) Reset()         { *m = S2C_LoginFinish{} }
func (m *S2C_LoginFinish) String() string { return proto.CompactTextString(m) }
func (*S2C_LoginFinish) ProtoMessage()    {}
func (*S2C_LoginFinish) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8ef43988e3693e5, []int{5}
}

func (m *S2C_LoginFinish) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C_LoginFinish.Unmarshal(m, b)
}
func (m *S2C_LoginFinish) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C_LoginFinish.Marshal(b, m, deterministic)
}
func (m *S2C_LoginFinish) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C_LoginFinish.Merge(m, src)
}
func (m *S2C_LoginFinish) XXX_Size() int {
	return xxx_messageInfo_S2C_LoginFinish.Size(m)
}
func (m *S2C_LoginFinish) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C_LoginFinish.DiscardUnknown(m)
}

var xxx_messageInfo_S2C_LoginFinish proto.InternalMessageInfo

func init() {
	proto.RegisterType((*C2S_Login)(nil), "msg.C2S_Login")
	proto.RegisterType((*S2C_Login)(nil), "msg.S2C_Login")
	proto.RegisterType((*C2S_CreateCharacter)(nil), "msg.C2S_CreateCharacter")
	proto.RegisterType((*S2C_CreateCharacter)(nil), "msg.S2C_CreateCharacter")
	proto.RegisterType((*S2C_Disconnect)(nil), "msg.S2C_Disconnect")
	proto.RegisterType((*S2C_LoginFinish)(nil), "msg.S2C_LoginFinish")
}

func init() {
	proto.RegisterFile("msg/msg_login.proto", fileDescriptor_f8ef43988e3693e5)
}

var fileDescriptor_f8ef43988e3693e5 = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x51, 0x4b, 0xf3, 0x30,
	0x14, 0x86, 0xe9, 0xba, 0x8e, 0xf5, 0x7c, 0xb0, 0x6f, 0x4b, 0x45, 0x06, 0x22, 0x8e, 0xe2, 0x45,
	0xaf, 0x1c, 0xcc, 0x7f, 0x60, 0x65, 0x30, 0x10, 0x84, 0xcc, 0x2b, 0x41, 0x4a, 0x6c, 0xcf, 0xda,
	0xe8, 0x9a, 0x94, 0x24, 0x0e, 0xfd, 0x35, 0xfe, 0x55, 0x49, 0x52, 0x86, 0x17, 0xbb, 0xf1, 0xee,
	0xcd, 0x03, 0xef, 0x93, 0x73, 0x12, 0x48, 0x5a, 0x5d, 0x2f, 0x5b, 0x5d, 0x17, 0x7b, 0x59, 0x73,
	0x71, 0xd3, 0x29, 0x69, 0x24, 0x09, 0x5b, 0x5d, 0xa7, 0x2f, 0x10, 0xe7, 0xab, 0x6d, 0xf1, 0x60,
	0x39, 0xb9, 0x04, 0x60, 0x65, 0x29, 0x3f, 0x84, 0x29, 0x78, 0x35, 0x0f, 0x16, 0x41, 0x16, 0xd2,
	0xb8, 0x27, 0x9b, 0x8a, 0x9c, 0x41, 0x64, 0xe4, 0x3b, 0x8a, 0xf9, 0x60, 0x11, 0x64, 0x31, 0xf5,
	0x07, 0x72, 0x01, 0xb1, 0x46, 0x75, 0x40, 0x65, 0x3b, 0xe1, 0x22, 0xc8, 0x22, 0x3a, 0xf6, 0x60,
	0x53, 0xa5, 0xdf, 0x01, 0xc4, 0xdb, 0x55, 0xde, 0xfb, 0x09, 0x0c, 0x4b, 0x59, 0xa1, 0x33, 0x47,
	0xd4, 0x65, 0x5b, 0xef, 0xf6, 0xec, 0xcb, 0xd7, 0x07, 0xee, 0xca, 0xb1, 0x07, 0x9b, 0x8a, 0x5c,
	0xc1, 0xbf, 0xde, 0x6d, 0x78, 0x8b, 0xce, 0x1e, 0x52, 0xf0, 0xe8, 0x89, 0xb7, 0x48, 0xce, 0x61,
	0x24, 0x77, 0x3b, 0x8d, 0x66, 0x3e, 0x74, 0xce, 0xfe, 0x44, 0x32, 0x98, 0xca, 0x0e, 0x45, 0xf1,
	0xbb, 0x1d, 0xb9, 0xf6, 0xc4, 0xf2, 0xed, 0xd1, 0x90, 0x3e, 0x42, 0x62, 0x1f, 0x20, 0x57, 0xc8,
	0x0c, 0xe6, 0x0d, 0x53, 0xac, 0x34, 0xa8, 0xec, 0xa8, 0x82, 0xb5, 0x7e, 0xd4, 0x98, 0xba, 0x6c,
	0x59, 0x83, 0xcc, 0x4f, 0x19, 0x51, 0x97, 0xc9, 0x14, 0x42, 0x8d, 0x9f, 0xfd, 0xde, 0x36, 0xa6,
	0x6b, 0x48, 0xec, 0xc6, 0x27, 0x84, 0x7f, 0xda, 0x3d, 0xbd, 0x86, 0x89, 0xf5, 0xdc, 0x73, 0x5d,
	0x4a, 0x21, 0xb0, 0x34, 0xa7, 0x14, 0xe9, 0x0c, 0xfe, 0x1f, 0xdf, 0x77, 0xcd, 0x05, 0xd7, 0xcd,
	0x5d, 0xf2, 0x3c, 0x3b, 0xd4, 0x45, 0xa7, 0xe4, 0xdb, 0xd2, 0x7d, 0xb4, 0xfd, 0xf8, 0xd7, 0x91,
	0x8b, 0xb7, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x31, 0xb7, 0xcb, 0x3c, 0x0a, 0x02, 0x00, 0x00,
}
