// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/common.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BigIntSimilar struct {
	Val                  float64  `protobuf:"fixed64,1,opt,name=val,proto3" json:"val,omitempty"`
	Tail                 int32    `protobuf:"varint,2,opt,name=tail,proto3" json:"tail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BigIntSimilar) Reset()         { *m = BigIntSimilar{} }
func (m *BigIntSimilar) String() string { return proto.CompactTextString(m) }
func (*BigIntSimilar) ProtoMessage()    {}
func (*BigIntSimilar) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{0}
}

func (m *BigIntSimilar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BigIntSimilar.Unmarshal(m, b)
}
func (m *BigIntSimilar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BigIntSimilar.Marshal(b, m, deterministic)
}
func (m *BigIntSimilar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BigIntSimilar.Merge(m, src)
}
func (m *BigIntSimilar) XXX_Size() int {
	return xxx_messageInfo_BigIntSimilar.Size(m)
}
func (m *BigIntSimilar) XXX_DiscardUnknown() {
	xxx_messageInfo_BigIntSimilar.DiscardUnknown(m)
}

var xxx_messageInfo_BigIntSimilar proto.InternalMessageInfo

func (m *BigIntSimilar) GetVal() float64 {
	if m != nil {
		return m.Val
	}
	return 0
}

func (m *BigIntSimilar) GetTail() int32 {
	if m != nil {
		return m.Tail
	}
	return 0
}

func init() {
	proto.RegisterType((*BigIntSimilar)(nil), "common.BigIntSimilar")
}

func init() {
	proto.RegisterFile("common/common.proto", fileDescriptor_8f954d82c0b891f6)
}

var fileDescriptor_8f954d82c0b891f6 = []byte{
	// 114 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x87, 0x50, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x6c, 0x10, 0x9e, 0x92,
	0x29, 0x17, 0xaf, 0x53, 0x66, 0xba, 0x67, 0x5e, 0x49, 0x70, 0x66, 0x6e, 0x66, 0x4e, 0x62, 0x91,
	0x90, 0x00, 0x17, 0x73, 0x59, 0x62, 0x8e, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x63, 0x10, 0x88, 0x29,
	0x24, 0xc4, 0xc5, 0x52, 0x92, 0x98, 0x99, 0x23, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x1a, 0x04, 0x66,
	0x3b, 0x89, 0x46, 0x09, 0x97, 0xa5, 0x17, 0x14, 0xe5, 0x67, 0xe9, 0x83, 0x8d, 0x83, 0x9a, 0x9d,
	0xc4, 0x06, 0xe6, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x2c, 0x3a, 0xbb, 0x87, 0x73, 0x00,
	0x00, 0x00,
}
