// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/thing.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Property struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Val                  int64    `protobuf:"varint,2,opt,name=val,proto3" json:"val,omitempty"`
	LastUpdateTs         int64    `protobuf:"varint,3,opt,name=last_update_ts,json=lastUpdateTs,proto3" json:"last_update_ts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Property) Reset()         { *m = Property{} }
func (m *Property) String() string { return proto.CompactTextString(m) }
func (*Property) ProtoMessage()    {}
func (*Property) Descriptor() ([]byte, []int) {
	return fileDescriptor_afe8f65441405ed6, []int{0}
}

func (m *Property) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Property.Unmarshal(m, b)
}
func (m *Property) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Property.Marshal(b, m, deterministic)
}
func (m *Property) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Property.Merge(m, src)
}
func (m *Property) XXX_Size() int {
	return xxx_messageInfo_Property.Size(m)
}
func (m *Property) XXX_DiscardUnknown() {
	xxx_messageInfo_Property.DiscardUnknown(m)
}

var xxx_messageInfo_Property proto.InternalMessageInfo

func (m *Property) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Property) GetVal() int64 {
	if m != nil {
		return m.Val
	}
	return 0
}

func (m *Property) GetLastUpdateTs() int64 {
	if m != nil {
		return m.LastUpdateTs
	}
	return 0
}

type BigProperty struct {
	Id                   int32          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Val                  *BigIntSimilar `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
	LastUpdateTs         int64          `protobuf:"varint,3,opt,name=last_update_ts,json=lastUpdateTs,proto3" json:"last_update_ts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BigProperty) Reset()         { *m = BigProperty{} }
func (m *BigProperty) String() string { return proto.CompactTextString(m) }
func (*BigProperty) ProtoMessage()    {}
func (*BigProperty) Descriptor() ([]byte, []int) {
	return fileDescriptor_afe8f65441405ed6, []int{1}
}

func (m *BigProperty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BigProperty.Unmarshal(m, b)
}
func (m *BigProperty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BigProperty.Marshal(b, m, deterministic)
}
func (m *BigProperty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BigProperty.Merge(m, src)
}
func (m *BigProperty) XXX_Size() int {
	return xxx_messageInfo_BigProperty.Size(m)
}
func (m *BigProperty) XXX_DiscardUnknown() {
	xxx_messageInfo_BigProperty.DiscardUnknown(m)
}

var xxx_messageInfo_BigProperty proto.InternalMessageInfo

func (m *BigProperty) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BigProperty) GetVal() *BigIntSimilar {
	if m != nil {
		return m.Val
	}
	return nil
}

func (m *BigProperty) GetLastUpdateTs() int64 {
	if m != nil {
		return m.LastUpdateTs
	}
	return 0
}

func init() {
	proto.RegisterType((*Property)(nil), "common.Property")
	proto.RegisterType((*BigProperty)(nil), "common.BigProperty")
}

func init() {
	proto.RegisterFile("common/thing.proto", fileDescriptor_afe8f65441405ed6)
}

var fileDescriptor_afe8f65441405ed6 = []byte{
	// 183 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4a, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x2f, 0xc9, 0xc8, 0xcc, 0x4b, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0x83, 0x88, 0x49, 0x09, 0x43, 0xe5, 0x20, 0x14, 0x44, 0x52, 0x29, 0x88, 0x8b, 0x23, 0xa0, 0x28,
	0xbf, 0x20, 0xb5, 0xa8, 0xa4, 0x52, 0x88, 0x8f, 0x8b, 0x29, 0x33, 0x45, 0x82, 0x51, 0x81, 0x51,
	0x83, 0x35, 0x88, 0x29, 0x33, 0x45, 0x48, 0x80, 0x8b, 0xb9, 0x2c, 0x31, 0x47, 0x82, 0x49, 0x81,
	0x51, 0x83, 0x39, 0x08, 0xc4, 0x14, 0x52, 0xe1, 0xe2, 0xcb, 0x49, 0x2c, 0x2e, 0x89, 0x2f, 0x2d,
	0x48, 0x49, 0x2c, 0x49, 0x8d, 0x2f, 0x29, 0x96, 0x60, 0x06, 0x4b, 0xf2, 0x80, 0x44, 0x43, 0xc1,
	0x82, 0x21, 0xc5, 0x4a, 0x39, 0x5c, 0xdc, 0x4e, 0x99, 0xe9, 0x38, 0x8d, 0x55, 0x47, 0x18, 0xcb,
	0x6d, 0x24, 0xaa, 0x07, 0x75, 0x8e, 0x53, 0x66, 0xba, 0x67, 0x5e, 0x49, 0x70, 0x66, 0x6e, 0x66,
	0x4e, 0x62, 0x11, 0x09, 0xb6, 0x39, 0x89, 0x46, 0x09, 0x97, 0xa5, 0x17, 0x14, 0xe5, 0x67, 0xe9,
	0x83, 0x7d, 0x04, 0xf5, 0x5e, 0x12, 0x1b, 0x98, 0x67, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x65,
	0x53, 0x4d, 0x9c, 0x12, 0x01, 0x00, 0x00,
}
