// Code generated by protoc-gen-go. DO NOT EDIT.
// source: masterrpc/msg_name_manage.proto

package masterrpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReqGrabPlayerName struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqGrabPlayerName) Reset()         { *m = ReqGrabPlayerName{} }
func (m *ReqGrabPlayerName) String() string { return proto.CompactTextString(m) }
func (*ReqGrabPlayerName) ProtoMessage()    {}
func (*ReqGrabPlayerName) Descriptor() ([]byte, []int) {
	return fileDescriptor_af5a5fdd062c9e9b, []int{0}
}

func (m *ReqGrabPlayerName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqGrabPlayerName.Unmarshal(m, b)
}
func (m *ReqGrabPlayerName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqGrabPlayerName.Marshal(b, m, deterministic)
}
func (m *ReqGrabPlayerName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqGrabPlayerName.Merge(m, src)
}
func (m *ReqGrabPlayerName) XXX_Size() int {
	return xxx_messageInfo_ReqGrabPlayerName.Size(m)
}
func (m *ReqGrabPlayerName) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqGrabPlayerName.DiscardUnknown(m)
}

var xxx_messageInfo_ReqGrabPlayerName proto.InternalMessageInfo

func (m *ReqGrabPlayerName) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RspGrabPlayerName struct {
	Suc                  bool     `protobuf:"varint,1,opt,name=suc,proto3" json:"suc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspGrabPlayerName) Reset()         { *m = RspGrabPlayerName{} }
func (m *RspGrabPlayerName) String() string { return proto.CompactTextString(m) }
func (*RspGrabPlayerName) ProtoMessage()    {}
func (*RspGrabPlayerName) Descriptor() ([]byte, []int) {
	return fileDescriptor_af5a5fdd062c9e9b, []int{1}
}

func (m *RspGrabPlayerName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspGrabPlayerName.Unmarshal(m, b)
}
func (m *RspGrabPlayerName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspGrabPlayerName.Marshal(b, m, deterministic)
}
func (m *RspGrabPlayerName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspGrabPlayerName.Merge(m, src)
}
func (m *RspGrabPlayerName) XXX_Size() int {
	return xxx_messageInfo_RspGrabPlayerName.Size(m)
}
func (m *RspGrabPlayerName) XXX_DiscardUnknown() {
	xxx_messageInfo_RspGrabPlayerName.DiscardUnknown(m)
}

var xxx_messageInfo_RspGrabPlayerName proto.InternalMessageInfo

func (m *RspGrabPlayerName) GetSuc() bool {
	if m != nil {
		return m.Suc
	}
	return false
}

type NotifyReleasePlayerName struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyReleasePlayerName) Reset()         { *m = NotifyReleasePlayerName{} }
func (m *NotifyReleasePlayerName) String() string { return proto.CompactTextString(m) }
func (*NotifyReleasePlayerName) ProtoMessage()    {}
func (*NotifyReleasePlayerName) Descriptor() ([]byte, []int) {
	return fileDescriptor_af5a5fdd062c9e9b, []int{2}
}

func (m *NotifyReleasePlayerName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyReleasePlayerName.Unmarshal(m, b)
}
func (m *NotifyReleasePlayerName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyReleasePlayerName.Marshal(b, m, deterministic)
}
func (m *NotifyReleasePlayerName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyReleasePlayerName.Merge(m, src)
}
func (m *NotifyReleasePlayerName) XXX_Size() int {
	return xxx_messageInfo_NotifyReleasePlayerName.Size(m)
}
func (m *NotifyReleasePlayerName) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyReleasePlayerName.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyReleasePlayerName proto.InternalMessageInfo

func (m *NotifyReleasePlayerName) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ReqGrabGuildName struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqGrabGuildName) Reset()         { *m = ReqGrabGuildName{} }
func (m *ReqGrabGuildName) String() string { return proto.CompactTextString(m) }
func (*ReqGrabGuildName) ProtoMessage()    {}
func (*ReqGrabGuildName) Descriptor() ([]byte, []int) {
	return fileDescriptor_af5a5fdd062c9e9b, []int{3}
}

func (m *ReqGrabGuildName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqGrabGuildName.Unmarshal(m, b)
}
func (m *ReqGrabGuildName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqGrabGuildName.Marshal(b, m, deterministic)
}
func (m *ReqGrabGuildName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqGrabGuildName.Merge(m, src)
}
func (m *ReqGrabGuildName) XXX_Size() int {
	return xxx_messageInfo_ReqGrabGuildName.Size(m)
}
func (m *ReqGrabGuildName) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqGrabGuildName.DiscardUnknown(m)
}

var xxx_messageInfo_ReqGrabGuildName proto.InternalMessageInfo

func (m *ReqGrabGuildName) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RspGrabGuildName struct {
	Suc                  bool     `protobuf:"varint,1,opt,name=suc,proto3" json:"suc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspGrabGuildName) Reset()         { *m = RspGrabGuildName{} }
func (m *RspGrabGuildName) String() string { return proto.CompactTextString(m) }
func (*RspGrabGuildName) ProtoMessage()    {}
func (*RspGrabGuildName) Descriptor() ([]byte, []int) {
	return fileDescriptor_af5a5fdd062c9e9b, []int{4}
}

func (m *RspGrabGuildName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspGrabGuildName.Unmarshal(m, b)
}
func (m *RspGrabGuildName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspGrabGuildName.Marshal(b, m, deterministic)
}
func (m *RspGrabGuildName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspGrabGuildName.Merge(m, src)
}
func (m *RspGrabGuildName) XXX_Size() int {
	return xxx_messageInfo_RspGrabGuildName.Size(m)
}
func (m *RspGrabGuildName) XXX_DiscardUnknown() {
	xxx_messageInfo_RspGrabGuildName.DiscardUnknown(m)
}

var xxx_messageInfo_RspGrabGuildName proto.InternalMessageInfo

func (m *RspGrabGuildName) GetSuc() bool {
	if m != nil {
		return m.Suc
	}
	return false
}

type NotifyReleaseGuildName struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyReleaseGuildName) Reset()         { *m = NotifyReleaseGuildName{} }
func (m *NotifyReleaseGuildName) String() string { return proto.CompactTextString(m) }
func (*NotifyReleaseGuildName) ProtoMessage()    {}
func (*NotifyReleaseGuildName) Descriptor() ([]byte, []int) {
	return fileDescriptor_af5a5fdd062c9e9b, []int{5}
}

func (m *NotifyReleaseGuildName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyReleaseGuildName.Unmarshal(m, b)
}
func (m *NotifyReleaseGuildName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyReleaseGuildName.Marshal(b, m, deterministic)
}
func (m *NotifyReleaseGuildName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyReleaseGuildName.Merge(m, src)
}
func (m *NotifyReleaseGuildName) XXX_Size() int {
	return xxx_messageInfo_NotifyReleaseGuildName.Size(m)
}
func (m *NotifyReleaseGuildName) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyReleaseGuildName.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyReleaseGuildName proto.InternalMessageInfo

func (m *NotifyReleaseGuildName) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*ReqGrabPlayerName)(nil), "masterrpc.ReqGrabPlayerName")
	proto.RegisterType((*RspGrabPlayerName)(nil), "masterrpc.RspGrabPlayerName")
	proto.RegisterType((*NotifyReleasePlayerName)(nil), "masterrpc.NotifyReleasePlayerName")
	proto.RegisterType((*ReqGrabGuildName)(nil), "masterrpc.ReqGrabGuildName")
	proto.RegisterType((*RspGrabGuildName)(nil), "masterrpc.RspGrabGuildName")
	proto.RegisterType((*NotifyReleaseGuildName)(nil), "masterrpc.NotifyReleaseGuildName")
}

func init() {
	proto.RegisterFile("masterrpc/msg_name_manage.proto", fileDescriptor_af5a5fdd062c9e9b)
}

var fileDescriptor_af5a5fdd062c9e9b = []byte{
	// 188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xcf, 0x4d, 0x2c, 0x2e,
	0x49, 0x2d, 0x2a, 0x2a, 0x48, 0xd6, 0xcf, 0x2d, 0x4e, 0x8f, 0xcf, 0x4b, 0xcc, 0x4d, 0x8d, 0xcf,
	0x4d, 0xcc, 0x4b, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x2b, 0x50,
	0x52, 0xe7, 0x12, 0x0c, 0x4a, 0x2d, 0x74, 0x2f, 0x4a, 0x4c, 0x0a, 0xc8, 0x49, 0xac, 0x4c, 0x2d,
	0xf2, 0x4b, 0xcc, 0x4d, 0x15, 0x12, 0xe2, 0x62, 0x01, 0x69, 0x92, 0x60, 0x54, 0x60, 0xd4, 0xe0,
	0x0c, 0x02, 0xb3, 0x95, 0x54, 0xb9, 0x04, 0x83, 0x8a, 0x0b, 0xd0, 0x14, 0x0a, 0x70, 0x31, 0x17,
	0x97, 0x26, 0x83, 0xd5, 0x71, 0x04, 0x81, 0x98, 0x4a, 0xba, 0x5c, 0xe2, 0x7e, 0xf9, 0x25, 0x99,
	0x69, 0x95, 0x41, 0xa9, 0x39, 0xa9, 0x89, 0xc5, 0xa9, 0x04, 0x4c, 0x55, 0xe3, 0x12, 0x80, 0x5a,
	0xef, 0x5e, 0x9a, 0x99, 0x93, 0x82, 0x53, 0x9d, 0x0a, 0x97, 0x00, 0xd4, 0x76, 0x84, 0x3a, 0x4c,
	0xcb, 0x75, 0xb8, 0xc4, 0x50, 0x2c, 0xc7, 0x6b, 0xa6, 0x93, 0x44, 0x94, 0x58, 0x59, 0x7a, 0x41,
	0x51, 0x7e, 0x96, 0x3e, 0x38, 0x54, 0xf4, 0xe1, 0x81, 0x92, 0xc4, 0x06, 0x16, 0x30, 0x06, 0x04,
	0x00, 0x00, 0xff, 0xff, 0xf0, 0x6d, 0x17, 0xf1, 0x49, 0x01, 0x00, 0x00,
}
