// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rechargerpc/msg_recharge.proto

package rechargerpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReqCreateOrder struct {
	AccountId            int64    `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	ServerId             int32    `protobuf:"varint,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	PlayerId             int64    `protobuf:"varint,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	LocalProductId       int32    `protobuf:"varint,4,opt,name=local_product_id,json=localProductId,proto3" json:"local_product_id,omitempty"`
	SdkProductId         string   `protobuf:"bytes,5,opt,name=sdk_product_id,json=sdkProductId,proto3" json:"sdk_product_id,omitempty"`
	Currency             string   `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount               int64    `protobuf:"varint,7,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqCreateOrder) Reset()         { *m = ReqCreateOrder{} }
func (m *ReqCreateOrder) String() string { return proto.CompactTextString(m) }
func (*ReqCreateOrder) ProtoMessage()    {}
func (*ReqCreateOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_fef49e4ace779492, []int{0}
}

func (m *ReqCreateOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCreateOrder.Unmarshal(m, b)
}
func (m *ReqCreateOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCreateOrder.Marshal(b, m, deterministic)
}
func (m *ReqCreateOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCreateOrder.Merge(m, src)
}
func (m *ReqCreateOrder) XXX_Size() int {
	return xxx_messageInfo_ReqCreateOrder.Size(m)
}
func (m *ReqCreateOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCreateOrder.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCreateOrder proto.InternalMessageInfo

func (m *ReqCreateOrder) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *ReqCreateOrder) GetServerId() int32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

func (m *ReqCreateOrder) GetPlayerId() int64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *ReqCreateOrder) GetLocalProductId() int32 {
	if m != nil {
		return m.LocalProductId
	}
	return 0
}

func (m *ReqCreateOrder) GetSdkProductId() string {
	if m != nil {
		return m.SdkProductId
	}
	return ""
}

func (m *ReqCreateOrder) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *ReqCreateOrder) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type RspCreateOrder struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	LocalOrderId         int64    `protobuf:"varint,2,opt,name=local_order_id,json=localOrderId,proto3" json:"local_order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspCreateOrder) Reset()         { *m = RspCreateOrder{} }
func (m *RspCreateOrder) String() string { return proto.CompactTextString(m) }
func (*RspCreateOrder) ProtoMessage()    {}
func (*RspCreateOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_fef49e4ace779492, []int{1}
}

func (m *RspCreateOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspCreateOrder.Unmarshal(m, b)
}
func (m *RspCreateOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspCreateOrder.Marshal(b, m, deterministic)
}
func (m *RspCreateOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspCreateOrder.Merge(m, src)
}
func (m *RspCreateOrder) XXX_Size() int {
	return xxx_messageInfo_RspCreateOrder.Size(m)
}
func (m *RspCreateOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_RspCreateOrder.DiscardUnknown(m)
}

var xxx_messageInfo_RspCreateOrder proto.InternalMessageInfo

func (m *RspCreateOrder) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RspCreateOrder) GetLocalOrderId() int64 {
	if m != nil {
		return m.LocalOrderId
	}
	return 0
}

func init() {
	proto.RegisterType((*ReqCreateOrder)(nil), "rechargerpc.ReqCreateOrder")
	proto.RegisterType((*RspCreateOrder)(nil), "rechargerpc.RspCreateOrder")
}

func init() {
	proto.RegisterFile("rechargerpc/msg_recharge.proto", fileDescriptor_fef49e4ace779492)
}

var fileDescriptor_fef49e4ace779492 = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xc1, 0x4e, 0x83, 0x40,
	0x10, 0x86, 0x83, 0x14, 0x84, 0xb1, 0x21, 0x66, 0x0f, 0x86, 0xd4, 0x68, 0x48, 0xe3, 0x81, 0x93,
	0x1c, 0x7c, 0x03, 0x3d, 0xe1, 0x45, 0xb3, 0x47, 0x2f, 0x64, 0xdd, 0x9d, 0xa0, 0x96, 0x76, 0xd7,
	0x01, 0x9a, 0xf4, 0xa1, 0x7d, 0x07, 0xc3, 0x6c, 0xab, 0xdc, 0x76, 0xbe, 0x7f, 0x66, 0xf6, 0xff,
	0x07, 0x6e, 0x09, 0xf5, 0x87, 0xa2, 0x16, 0xc9, 0xe9, 0x6a, 0xdb, 0xb7, 0xcd, 0xa9, 0xbe, 0x77,
	0x64, 0x07, 0x2b, 0x2e, 0x66, 0xfa, 0xfa, 0x27, 0x80, 0x4c, 0xe2, 0xf7, 0x13, 0xa1, 0x1a, 0xf0,
	0x85, 0x0c, 0x92, 0xb8, 0x01, 0x50, 0x5a, 0xdb, 0x71, 0x37, 0x34, 0x9f, 0x26, 0x0f, 0x8a, 0xa0,
	0x0c, 0x65, 0x7a, 0x24, 0xb5, 0x11, 0xd7, 0x90, 0xf6, 0x48, 0x7b, 0xa4, 0x49, 0x3d, 0x2b, 0x82,
	0x32, 0x92, 0x89, 0x07, 0x5e, 0x74, 0x9d, 0x3a, 0x78, 0x31, 0xe4, 0xd1, 0xc4, 0x83, 0xda, 0x88,
	0x12, 0x2e, 0x3b, 0xab, 0x55, 0xd7, 0x38, 0xb2, 0x66, 0xd4, 0xbc, 0x7e, 0xc1, 0x0b, 0x32, 0xe6,
	0xaf, 0x1e, 0xd7, 0x46, 0xdc, 0x41, 0xd6, 0x9b, 0xcd, 0xbc, 0x2f, 0x2a, 0x82, 0x32, 0x95, 0xcb,
	0xde, 0x6c, 0xfe, 0xbb, 0x56, 0x90, 0xe8, 0x91, 0x08, 0x77, 0xfa, 0x90, 0xc7, 0xac, 0xff, 0xd5,
	0xe2, 0x0a, 0x62, 0xb5, 0x9d, 0x1c, 0xe7, 0xe7, 0xec, 0xe2, 0x58, 0xad, 0x9f, 0x21, 0x93, 0xbd,
	0x9b, 0xc7, 0x15, 0xb0, 0xd0, 0xd6, 0x20, 0x07, 0x8d, 0x24, 0xbf, 0xa7, 0xff, 0xbd, 0x53, 0x3b,
	0xb5, 0x9c, 0x82, 0x86, 0x72, 0xc9, 0x94, 0xe7, 0x6a, 0xf3, 0xb8, 0x7a, 0xcb, 0xf7, 0xad, 0x23,
	0xfb, 0x55, 0xf1, 0x61, 0xab, 0xd9, 0x5d, 0xdf, 0x63, 0x46, 0x0f, 0xbf, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xc1, 0x57, 0x0b, 0x4e, 0x8d, 0x01, 0x00, 0x00,
}
