// Code generated by protoc-gen-go. DO NOT EDIT.
// source: loginrpc/msg_login.proto

package loginrpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReqLogin struct {
	AccountId            int64    `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Ip                   string   `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	ServerId             int32    `protobuf:"varint,4,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqLogin) Reset()         { *m = ReqLogin{} }
func (m *ReqLogin) String() string { return proto.CompactTextString(m) }
func (*ReqLogin) ProtoMessage()    {}
func (*ReqLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_30e0aad429e3205c, []int{0}
}

func (m *ReqLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqLogin.Unmarshal(m, b)
}
func (m *ReqLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqLogin.Marshal(b, m, deterministic)
}
func (m *ReqLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqLogin.Merge(m, src)
}
func (m *ReqLogin) XXX_Size() int {
	return xxx_messageInfo_ReqLogin.Size(m)
}
func (m *ReqLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqLogin.DiscardUnknown(m)
}

var xxx_messageInfo_ReqLogin proto.InternalMessageInfo

func (m *ReqLogin) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *ReqLogin) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ReqLogin) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *ReqLogin) GetServerId() int32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

type RspLogin struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Rnd                  uint64   `protobuf:"varint,2,opt,name=rnd,proto3" json:"rnd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspLogin) Reset()         { *m = RspLogin{} }
func (m *RspLogin) String() string { return proto.CompactTextString(m) }
func (*RspLogin) ProtoMessage()    {}
func (*RspLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_30e0aad429e3205c, []int{1}
}

func (m *RspLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspLogin.Unmarshal(m, b)
}
func (m *RspLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspLogin.Marshal(b, m, deterministic)
}
func (m *RspLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspLogin.Merge(m, src)
}
func (m *RspLogin) XXX_Size() int {
	return xxx_messageInfo_RspLogin.Size(m)
}
func (m *RspLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_RspLogin.DiscardUnknown(m)
}

var xxx_messageInfo_RspLogin proto.InternalMessageInfo

func (m *RspLogin) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RspLogin) GetRnd() uint64 {
	if m != nil {
		return m.Rnd
	}
	return 0
}

type NotifyLogout struct {
	AccountId            int64    `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	ServerId             int32    `protobuf:"varint,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Rnd                  uint64   `protobuf:"varint,3,opt,name=rnd,proto3" json:"rnd,omitempty"`
	PlayerId             int64    `protobuf:"varint,4,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Combat               int64    `protobuf:"varint,6,opt,name=combat,proto3" json:"combat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyLogout) Reset()         { *m = NotifyLogout{} }
func (m *NotifyLogout) String() string { return proto.CompactTextString(m) }
func (*NotifyLogout) ProtoMessage()    {}
func (*NotifyLogout) Descriptor() ([]byte, []int) {
	return fileDescriptor_30e0aad429e3205c, []int{2}
}

func (m *NotifyLogout) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyLogout.Unmarshal(m, b)
}
func (m *NotifyLogout) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyLogout.Marshal(b, m, deterministic)
}
func (m *NotifyLogout) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyLogout.Merge(m, src)
}
func (m *NotifyLogout) XXX_Size() int {
	return xxx_messageInfo_NotifyLogout.Size(m)
}
func (m *NotifyLogout) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyLogout.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyLogout proto.InternalMessageInfo

func (m *NotifyLogout) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *NotifyLogout) GetServerId() int32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

func (m *NotifyLogout) GetRnd() uint64 {
	if m != nil {
		return m.Rnd
	}
	return 0
}

func (m *NotifyLogout) GetPlayerId() int64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *NotifyLogout) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NotifyLogout) GetCombat() int64 {
	if m != nil {
		return m.Combat
	}
	return 0
}

type ReqKick struct {
	AccountId            int64    `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqKick) Reset()         { *m = ReqKick{} }
func (m *ReqKick) String() string { return proto.CompactTextString(m) }
func (*ReqKick) ProtoMessage()    {}
func (*ReqKick) Descriptor() ([]byte, []int) {
	return fileDescriptor_30e0aad429e3205c, []int{3}
}

func (m *ReqKick) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqKick.Unmarshal(m, b)
}
func (m *ReqKick) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqKick.Marshal(b, m, deterministic)
}
func (m *ReqKick) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqKick.Merge(m, src)
}
func (m *ReqKick) XXX_Size() int {
	return xxx_messageInfo_ReqKick.Size(m)
}
func (m *ReqKick) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqKick.DiscardUnknown(m)
}

var xxx_messageInfo_ReqKick proto.InternalMessageInfo

func (m *ReqKick) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

type RspKick struct {
	Suc                  bool     `protobuf:"varint,1,opt,name=suc,proto3" json:"suc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspKick) Reset()         { *m = RspKick{} }
func (m *RspKick) String() string { return proto.CompactTextString(m) }
func (*RspKick) ProtoMessage()    {}
func (*RspKick) Descriptor() ([]byte, []int) {
	return fileDescriptor_30e0aad429e3205c, []int{4}
}

func (m *RspKick) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspKick.Unmarshal(m, b)
}
func (m *RspKick) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspKick.Marshal(b, m, deterministic)
}
func (m *RspKick) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspKick.Merge(m, src)
}
func (m *RspKick) XXX_Size() int {
	return xxx_messageInfo_RspKick.Size(m)
}
func (m *RspKick) XXX_DiscardUnknown() {
	xxx_messageInfo_RspKick.DiscardUnknown(m)
}

var xxx_messageInfo_RspKick proto.InternalMessageInfo

func (m *RspKick) GetSuc() bool {
	if m != nil {
		return m.Suc
	}
	return false
}

func init() {
	proto.RegisterType((*ReqLogin)(nil), "loginrpc.ReqLogin")
	proto.RegisterType((*RspLogin)(nil), "loginrpc.RspLogin")
	proto.RegisterType((*NotifyLogout)(nil), "loginrpc.NotifyLogout")
	proto.RegisterType((*ReqKick)(nil), "loginrpc.ReqKick")
	proto.RegisterType((*RspKick)(nil), "loginrpc.RspKick")
}

func init() {
	proto.RegisterFile("loginrpc/msg_login.proto", fileDescriptor_30e0aad429e3205c)
}

var fileDescriptor_30e0aad429e3205c = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x51, 0xbd, 0x6a, 0xc3, 0x30,
	0x18, 0xc4, 0x56, 0x9c, 0x28, 0x1f, 0xa5, 0x04, 0xd1, 0x1f, 0x41, 0x28, 0x04, 0x4f, 0x9e, 0x9a,
	0x42, 0xdf, 0xa0, 0x5b, 0x68, 0xe8, 0xa0, 0xb1, 0x4b, 0x70, 0x24, 0xd5, 0xa8, 0x89, 0x2d, 0x45,
	0x96, 0x03, 0x79, 0xa0, 0xbe, 0x67, 0xd1, 0xe7, 0xb8, 0x25, 0x53, 0xb6, 0xbb, 0xd3, 0x71, 0x77,
	0xe2, 0x03, 0xbe, 0xb7, 0x95, 0x69, 0xbc, 0x93, 0xcb, 0xba, 0xad, 0x36, 0x48, 0x9e, 0x9d, 0xb7,
	0xc1, 0x32, 0x3a, 0xbc, 0xe4, 0x7b, 0xa0, 0x42, 0x1f, 0xd6, 0x91, 0xb2, 0x27, 0x80, 0x52, 0x4a,
	0xdb, 0x35, 0x61, 0x63, 0x14, 0x4f, 0x16, 0x49, 0x41, 0xc4, 0xf4, 0xac, 0xac, 0x14, 0xbb, 0x83,
	0x2c, 0xd8, 0x9d, 0x6e, 0x78, 0xba, 0x48, 0x8a, 0xa9, 0xe8, 0x09, 0xbb, 0x85, 0xd4, 0x38, 0x4e,
	0x50, 0x4a, 0x8d, 0x63, 0x73, 0x98, 0xb6, 0xda, 0x1f, 0xb5, 0x8f, 0x19, 0xa3, 0x45, 0x52, 0x64,
	0x82, 0xf6, 0xc2, 0x4a, 0xe5, 0x2f, 0x40, 0x45, 0xeb, 0xfa, 0x36, 0x06, 0x23, 0x69, 0x95, 0xc6,
	0x9e, 0x4c, 0x20, 0x66, 0x33, 0x20, 0xbe, 0x51, 0x58, 0x30, 0x12, 0x11, 0xe6, 0x3f, 0x09, 0xdc,
	0x7c, 0xd8, 0x60, 0xbe, 0x4e, 0x6b, 0x5b, 0xd9, 0x2e, 0x5c, 0x1b, 0x79, 0x51, 0x9f, 0x5e, 0xd6,
	0x0f, 0xf1, 0xe4, 0x2f, 0x3e, 0xda, 0xdd, 0xbe, 0x3c, 0xfd, 0xaf, 0x25, 0x82, 0xf6, 0xc2, 0x4a,
	0xc5, 0x85, 0x4d, 0x59, 0x6b, 0x9e, 0xe1, 0xe7, 0x10, 0xb3, 0x07, 0x18, 0x4b, 0x5b, 0x6f, 0xcb,
	0xc0, 0xc7, 0xe8, 0x3e, 0xb3, 0xbc, 0x80, 0x89, 0xd0, 0x87, 0x77, 0x23, 0x77, 0x57, 0x16, 0xe6,
	0x73, 0x98, 0x88, 0xd6, 0xa1, 0x73, 0x06, 0xa4, 0xed, 0x24, 0x5a, 0xa8, 0x88, 0xf0, 0xed, 0xf1,
	0xf3, 0xfe, 0x58, 0x39, 0x6f, 0xbf, 0x97, 0x78, 0xa8, 0xe5, 0x70, 0xa7, 0xed, 0x18, 0xf9, 0xeb,
	0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9e, 0xa7, 0x6a, 0x9f, 0xd4, 0x01, 0x00, 0x00,
}
