// Code generated by protoc-gen-go. DO NOT EDIT.
// source: loginrpc/msg_load_balance.proto

package loginrpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReqGameServerLoad struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqGameServerLoad) Reset()         { *m = ReqGameServerLoad{} }
func (m *ReqGameServerLoad) String() string { return proto.CompactTextString(m) }
func (*ReqGameServerLoad) ProtoMessage()    {}
func (*ReqGameServerLoad) Descriptor() ([]byte, []int) {
	return fileDescriptor_55fea90fab0045ba, []int{0}
}

func (m *ReqGameServerLoad) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqGameServerLoad.Unmarshal(m, b)
}
func (m *ReqGameServerLoad) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqGameServerLoad.Marshal(b, m, deterministic)
}
func (m *ReqGameServerLoad) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqGameServerLoad.Merge(m, src)
}
func (m *ReqGameServerLoad) XXX_Size() int {
	return xxx_messageInfo_ReqGameServerLoad.Size(m)
}
func (m *ReqGameServerLoad) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqGameServerLoad.DiscardUnknown(m)
}

var xxx_messageInfo_ReqGameServerLoad proto.InternalMessageInfo

type RspGameServerLoad struct {
	OnlineNum            int32    `protobuf:"varint,1,opt,name=online_num,json=onlineNum,proto3" json:"online_num,omitempty"`
	TotalNum             int32    `protobuf:"varint,2,opt,name=total_num,json=totalNum,proto3" json:"total_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspGameServerLoad) Reset()         { *m = RspGameServerLoad{} }
func (m *RspGameServerLoad) String() string { return proto.CompactTextString(m) }
func (*RspGameServerLoad) ProtoMessage()    {}
func (*RspGameServerLoad) Descriptor() ([]byte, []int) {
	return fileDescriptor_55fea90fab0045ba, []int{1}
}

func (m *RspGameServerLoad) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspGameServerLoad.Unmarshal(m, b)
}
func (m *RspGameServerLoad) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspGameServerLoad.Marshal(b, m, deterministic)
}
func (m *RspGameServerLoad) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspGameServerLoad.Merge(m, src)
}
func (m *RspGameServerLoad) XXX_Size() int {
	return xxx_messageInfo_RspGameServerLoad.Size(m)
}
func (m *RspGameServerLoad) XXX_DiscardUnknown() {
	xxx_messageInfo_RspGameServerLoad.DiscardUnknown(m)
}

var xxx_messageInfo_RspGameServerLoad proto.InternalMessageInfo

func (m *RspGameServerLoad) GetOnlineNum() int32 {
	if m != nil {
		return m.OnlineNum
	}
	return 0
}

func (m *RspGameServerLoad) GetTotalNum() int32 {
	if m != nil {
		return m.TotalNum
	}
	return 0
}

func init() {
	proto.RegisterType((*ReqGameServerLoad)(nil), "loginrpc.ReqGameServerLoad")
	proto.RegisterType((*RspGameServerLoad)(nil), "loginrpc.RspGameServerLoad")
}

func init() {
	proto.RegisterFile("loginrpc/msg_load_balance.proto", fileDescriptor_55fea90fab0045ba)
}

var fileDescriptor_55fea90fab0045ba = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xcf, 0xc9, 0x4f, 0xcf,
	0xcc, 0x2b, 0x2a, 0x48, 0xd6, 0xcf, 0x2d, 0x4e, 0x8f, 0xcf, 0xc9, 0x4f, 0x4c, 0x89, 0x4f, 0x4a,
	0xcc, 0x49, 0xcc, 0x4b, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0x29, 0x50,
	0x12, 0xe6, 0x12, 0x0c, 0x4a, 0x2d, 0x74, 0x4f, 0xcc, 0x4d, 0x0d, 0x4e, 0x2d, 0x2a, 0x4b, 0x2d,
	0xf2, 0xc9, 0x4f, 0x4c, 0x51, 0xf2, 0xe7, 0x12, 0x0c, 0x2a, 0x2e, 0x40, 0x15, 0x14, 0x92, 0xe5,
	0xe2, 0xca, 0xcf, 0xcb, 0xc9, 0xcc, 0x4b, 0x8d, 0xcf, 0x2b, 0xcd, 0x95, 0x60, 0x54, 0x60, 0xd4,
	0x60, 0x0d, 0xe2, 0x84, 0x88, 0xf8, 0x95, 0xe6, 0x0a, 0x49, 0x73, 0x71, 0x96, 0xe4, 0x97, 0x24,
	0xe6, 0x80, 0x65, 0x99, 0xc0, 0xb2, 0x1c, 0x60, 0x01, 0xbf, 0xd2, 0x5c, 0x27, 0xf1, 0x28, 0xd1,
	0xb2, 0xf4, 0x82, 0xa2, 0xfc, 0x2c, 0x7d, 0xb0, 0xfd, 0xfa, 0x30, 0xeb, 0x93, 0xd8, 0xc0, 0x7c,
	0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x09, 0x35, 0x5f, 0x95, 0xb2, 0x00, 0x00, 0x00,
}
